version: 2.1

workflows:
  version: 2
  default:
    jobs:
      - default:
          filters:
            branches:
              only: master

jobs:
  default:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run:
          command: |
            chmod +x prepare.sh
            ./prepare.sh
      - store_artifacts:
          path: output