version: 2.1

workflows:
  version: 2
  default:
    jobs:
      - default:
          filters:
            branches:
              only: master

jobs:
  default:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run:
          command: |
            echo ${GITHUB_TOKEN} | docker login -u raknam --password-stdin docker.pkg.github.com
            docker run \
              --rm \
              --privileged \
              -v ${PWD}:/build:ro \
              -v ${PWD}/packer_cache:/build/packer_cache \
              -v ${PWD}/output:/build/output \
              docker.pkg.github.com/raknam/rpi-buster-image-prepare/packer-builder-arm build -debug rpi-zero.json
      - store_artifacts:
          path: output